<?php


/**
 * Implements hook_init().
 */
function sigma_init() {
  require_once 'includes/Sigma.class.php';
}


/**
 * Implements hook_menu().
 */
function sigma_menu() {
  $items = array();

  $items['admin/config/services/sigma'] = array(
    'title' => 'Sigma Instagram',
    'description' => t('Sigma Instagram settings.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sigma_settings_form'),
    'access callback' => 'user_access',
    'access arguments' => array('administer sigma instagram'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/sigma.admin.inc',
  );

  $items['admin/config/services/sigma/settings'] = array(
    'title' => 'Sigma Instagram Settings',
    'description' => t('Sigma Instagram settings.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sigma_settings_form'),
    'access callback' => 'user_access',
    'access arguments' => array('administer sigma instagram'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'file' => 'includes/sigma.admin.inc',
    'weight' => 0,
  );

  //$items['admin/config/services/sigma/settings'] = array(
  //  'title' => 'Instagram',
  //  'description' => t('Instagram settings form.'),
  //  'page callback' => 'drupal_get_form',
  //  'page arguments' => array('sigma_settings_form'),
  //  'access callback' => 'user_access',
  //  'access arguments' => array('administer sigma instagram'),
  //  'type' => MENU_LOCAL_TASK,
  //  'file' => 'includes/sigma.admin.inc',
  //  'weight' => 1,
  //);

  return $items;
}


/**
 * Implements hook_permission().
 */
function sigma_permission() {
  $permissions = array();

  $permissions['administer sigma instagram'] = array(
    'title' => t('Administer Sigma Instagram'),
    'description' => t('Perform administration tasks for Sigma Instagram.'),
  );

  return $permissions;
}
